name: Edge Entertainment
favicon: null
layout_spectrum: 0.4705232142005116
typography_spectrum: 0.9796157453674823
title: Edge Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6b6b6b'
    - '#999999'
    - '#3b3b3b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
